# Generated by Django 3.2.6 on 2022-04-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220409_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=225),
        ),
    ]
