# Generated by Django 3.2.6 on 2022-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220414_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=225),
        ),
    ]
