# Generated by Django 3.2.6 on 2022-04-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_plainproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plainproduct',
            options={'verbose_name': 'PlainProduct', 'verbose_name_plural': 'PlainProducts'},
        ),
    ]
