# Generated by Django 3.2.6 on 2022-05-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_plainproduct_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_design',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='custom_design',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='custom_design',
            name='logo',
        ),
    ]
