# Generated by Django 3.2.6 on 2022-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220501_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainproduct',
            name='image',
            field=models.ImageField(upload_to='plainproduct'),
        ),
    ]
