# Generated by Django 3.2.6 on 2022-05-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_custom_design_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_delivered',
        ),
    ]
